Make noted changes to Student and Instructor tables
Changes being made:
 - userName is now the PK for both tables and is not allowed to be NULL
 - ID attribute is removed from Instructor
 - order of attributes has been changed
 - making userName be a FK to pg_role/pg_authid was discussed, but not
    possible. Attempting to do so results in the following error:
	ERROR:  permission denied: "pg_authid" is a system catalog
 - a trigger can be written to enforce the above constraint